name: Deploy Astro App with Prisma

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🔧 Generate Prisma Client
        run: npx prisma generate

      - name: 🧩 Push Prisma Schema to Neon
        run: npx prisma db push

      - name: 🚀 Build Astro Project
        run: npm run build